1.	Write a Python Program to Add Two Matrices?


In [4]:
x = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]

y = [[90, 80, 70],
     [60, 50, 40],
     [30, 20, 10]]

import numpy as np

answer = np.array(x) + np.array(y)
print(answer)

[[91 82 73]
 [64 55 46]
 [37 28 19]]


2.	Write a Python Program to Multiply Two Matrices?


In [5]:
x = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]

y = [[90, 80, 70],
     [60, 50, 40],
     [30, 20, 10]]

product = np.array(x)* np.array(y)
print(product)

[[ 90 160 210]
 [240 250 240]
 [210 160  90]]


3.	Write a Python Program to Transpose a Matrix?


In [8]:
x = [[1, 2, 3],
     [4, 5, 6]]

print(np.transpose(x))

[[1 4]
 [2 5]
 [3 6]]


4.	Write a Python Program to Sort Words in Alphabetic Order?


In [28]:
sentence = input("Enter a group of words: ")

words = [i.lower() for i in sentence.split()]
words.sort()

for i in words:
    print(i)

Enter a group of words: Join our offline Data Structures and Algorithms course led by experienced mentors from top tech companies.
algorithms
and
by
companies.
course
data
experienced
from
join
led
mentors
offline
our
structures
tech
top


5.	Write a Python Program to Remove Punctuation From a String?


In [29]:
import re

sentence = input("String with punctuations: ")

remove = re.sub(r'[^\w\s]', " ", sentence)

print("String without punctuation: ", remove)

String with punctuations: Hey! Welcome to - iNeuron :) Hope, you? enjoy& the course@
String without punctuation:  Hey  Welcome to   iNeuron    Hope  you  enjoy  the course 
